const ShopActionsTypes = {
	FETCH_COLLECTION_START: 'SHOP/FETCH_COLLECTION_START',
	FETCH_COLLECTION_SUCCESS: 'SHOP/FETCH_COLLECTION_SUCCESS',
	FETCH_COLLECTION_FAILURE: 'SHOP/FETCH_COLLECTION_FAILURE',
};

export default ShopActionsTypes;
