const ProductActionsTypes = {
	FETCH_COLLECTION_START: 'PRODUCT/FETCH_COLLECTION_START',
	FETCH_COLLECTION_SUCCESS: 'PRODUCT/FETCH_COLLECTION_SUCCESS',
	FETCH_COLLECTION_FAILURE: 'PRODUCT/FETCH_COLLECTION_FAILURE',
}

export default ProductActionsTypes
